import { ATLAS_ANALYSIS_CRS } from "./crs";
import type { AtlasLayerManifest } from "./types";

export const LAYER_REGISTRY: AtlasLayerManifest[] = [
  {
    id: "region.sido.boundary",
    title: "시도 경계",
    group: "administration",
    entityType: "region",
    role: "reference",
    geometryType: "polygon",
    sourceId: "sgis",
    fallbackSourceIds: ["vworld"],
    nativeIdField: "official_code",
    sourceCrs: "EPSG:5179",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["sido"],
    temporalType: "periodic",
    sourceFormats: ["shp", "json"],
    atlasFormats: ["geoparquet", "geopackage", "geojson"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    joinKey: "official_code",
    status: "partial",
    notes: "Independent reference boundary layer. Boundary snapshot/version is stored separately from the KIK code snapshot.",
  },
  {
    id: "region.sigungu.boundary",
    title: "시군구 경계",
    group: "administration",
    entityType: "region",
    role: "reference",
    geometryType: "polygon",
    sourceId: "sgis",
    fallbackSourceIds: ["vworld"],
    nativeIdField: "official_code",
    sourceCrs: "EPSG:5179",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["sigungu"],
    temporalType: "periodic",
    sourceFormats: ["shp", "json"],
    atlasFormats: ["geoparquet", "geopackage", "geojson"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    joinKey: "official_code",
    status: "partial",
    notes: "Independent reference boundary layer. A selected dong or grid analysis may still package this layer as context.",
  },
  {
    id: "region.admin-dong.boundary",
    title: "행정읍면동 경계",
    group: "administration",
    entityType: "region",
    role: "reference",
    geometryType: "polygon",
    sourceId: "sgis",
    fallbackSourceIds: ["vworld"],
    nativeIdField: "official_code",
    sourceCrs: "EPSG:5179",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["admin-dong"],
    temporalType: "periodic",
    sourceFormats: ["shp", "json"],
    atlasFormats: ["geoparquet", "geopackage", "geojson"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    joinKey: "official_code",
    status: "partial",
    notes: "Administrative boundary is independent from legal-dong geometry. Boundary version and valid period must be stored separately from the KIK official-code snapshot.",
  },
  {
    id: "region.legal-dong.boundary",
    title: "법정읍면동·법정동 경계",
    group: "administration",
    entityType: "region",
    role: "reference",
    geometryType: "polygon",
    sourceId: "vworld",
    fallbackSourceIds: ["data-go-kr"],
    nativeIdField: "official_code",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["legal-dong"],
    temporalType: "periodic",
    sourceFormats: ["wfs", "json", "gml", "shp"],
    atlasFormats: ["geoparquet", "geopackage", "geojson"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    joinKey: "official_code",
    status: "planned",
    notes: "Keep legal-dong geometry separate from administrative-dong geometry. Exact authoritative extractable provider/layer and source CRS still require runtime verification before status can be promoted.",
  },
  {
    id: "population.admin-dong.total",
    title: "행정동 총인구",
    group: "statistics",
    entityType: "statistic",
    geometryType: "none",
    sourceId: "sgis",
    fallbackSourceIds: ["kosis"],
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["admin-dong"],
    temporalType: "annual",
    sourceFormats: ["json"],
    atlasFormats: ["parquet", "csv", "json"],
    exportTargets: ["web", "data", "qgis", "mcp"],
    joinKey: "atlas_region_id",
    status: "available",
    notes: "Existing MVP SGIS administrative-dong statistics can populate this normalized indicator.",
  },
  {
    id: "population.grid-100m.total",
    title: "100m 격자 총인구",
    group: "statistics",
    entityType: "grid",
    geometryType: "polygon",
    sourceId: "sgis",
    nativeIdField: "native_grid_id",
    sourceCrs: "EPSG:5179",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["grid-100m"],
    temporalType: "annual",
    sourceFormats: ["shp", "txt", "csv"],
    atlasFormats: ["geoparquet", "geopackage", "geojson", "parquet"],
    exportTargets: ["web", "data", "qgis", "mcp"],
    joinKey: "native_grid_id",
    status: "planned",
    notes: "Preserve the SGIS/native grid identifier and namespace it as the Atlas grid ID.",
  },
  {
    id: "business.admin-dong.total",
    title: "행정동 사업체·종사자",
    group: "statistics",
    entityType: "statistic",
    geometryType: "none",
    sourceId: "sgis",
    fallbackSourceIds: ["kosis"],
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["admin-dong"],
    temporalType: "annual",
    sourceFormats: ["json"],
    atlasFormats: ["parquet", "csv", "json"],
    exportTargets: ["web", "data", "qgis", "mcp"],
    joinKey: "atlas_region_id",
    status: "available",
    notes: "Official aggregate business/worker statistics; not interchangeable with POI counts or licensing records.",
  },
  {
    id: "business.grid-100m.total",
    title: "100m 격자 사업체·종사자",
    group: "statistics",
    entityType: "grid",
    geometryType: "polygon",
    sourceId: "sgis",
    nativeIdField: "native_grid_id",
    sourceCrs: "EPSG:5179",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["grid-100m"],
    temporalType: "annual",
    sourceFormats: ["shp", "txt", "csv"],
    atlasFormats: ["geoparquet", "geopackage", "geojson", "parquet"],
    exportTargets: ["web", "data", "qgis", "mcp"],
    joinKey: "native_grid_id",
    status: "planned",
    notes: "Grid-level business statistics should remain distinct from individual business entities.",
  },
  {
    id: "built.buildings",
    title: "건물",
    group: "built",
    entityType: "feature",
    geometryType: "polygon",
    sourceId: "vworld",
    fallbackSourceIds: ["osm"],
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["feature"],
    temporalType: "periodic",
    sourceFormats: ["wfs", "json", "gml"],
    atlasFormats: ["geoparquet", "geopackage", "geojson", "pmtiles"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    status: "partial",
    notes: "VWorld is a candidate official/national provider; OSM remains immediate open context fallback until a verified layer allowlist is finalized.",
  },
  {
    id: "built.roads",
    title: "도로",
    group: "mobility",
    entityType: "feature",
    geometryType: "line",
    sourceId: "vworld",
    fallbackSourceIds: ["osm"],
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["feature"],
    temporalType: "periodic",
    sourceFormats: ["wfs", "json", "gml"],
    atlasFormats: ["geoparquet", "geopackage", "geojson", "pmtiles"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    status: "partial",
    notes: "Provider-specific road schemas will be normalized without forcing a permanent merge with POI or statistics.",
  },
  {
    id: "planning.cadastral",
    title: "지적/필지",
    group: "planning",
    entityType: "feature",
    geometryType: "polygon",
    sourceId: "vworld",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["feature"],
    temporalType: "periodic",
    sourceFormats: ["wfs", "wms", "gml", "json"],
    atlasFormats: ["geoparquet", "geopackage", "geojson", "pmtiles"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    status: "planned",
    notes: "WMS is suitable for display; extract/export should prefer a verified feature/data endpoint with layer-specific reuse terms.",
  },
  {
    id: "planning.zoning",
    title: "용도지역·도시계획",
    group: "planning",
    entityType: "feature",
    geometryType: "polygon",
    sourceId: "vworld",
    fallbackSourceIds: ["data-go-kr"],
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["feature"],
    temporalType: "periodic",
    sourceFormats: ["wfs", "wms", "gml", "json", "shp"],
    atlasFormats: ["geoparquet", "geopackage", "geojson", "pmtiles"],
    exportTargets: ["web", "data", "qgis", "cad", "mcp"],
    status: "planned",
    notes: "VWorld and data.go.kr/official planning files can coexist as provider/fallback options with provenance retained.",
  },
  {
    id: "places.medical",
    title: "공식 의료시설",
    group: "places",
    entityType: "feature",
    geometryType: "point",
    sourceId: "hira",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["feature"],
    temporalType: "realtime",
    sourceFormats: ["xml", "json"],
    atlasFormats: ["geojson", "geoparquet", "geopackage"],
    exportTargets: ["web", "data", "qgis", "mcp"],
    status: "available",
    notes: "Existing MVP official medical facility provider.",
  },
  {
    id: "places.live-poi",
    title: "실시간 POI",
    group: "places",
    entityType: "feature",
    geometryType: "point",
    sourceId: "kakao",
    fallbackSourceIds: ["naver", "google", "osm"],
    sourceCrs: "EPSG:4326",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["feature"],
    temporalType: "realtime",
    sourceFormats: ["json"],
    atlasFormats: ["geojson"],
    exportTargets: ["web"],
    status: "available",
    notes: "Request-time provider observations. Export/storage availability is provider-policy dependent and must not be generalized across POI providers.",
  },
  {
    id: "environment.satellite",
    title: "국내 위성영상",
    group: "environment",
    entityType: "raster",
    geometryType: "raster",
    sourceId: "ngii-satellite",
    analysisCrs: ATLAS_ANALYSIS_CRS,
    spatialLevels: ["raster-scene"],
    temporalType: "scene",
    sourceFormats: ["geotiff", "image", "metadata"],
    atlasFormats: ["cog", "geotiff", "json-metadata"],
    exportTargets: ["web", "data", "qgis", "mcp"],
    status: "planned",
    notes: "Keep imagery as an independent raster layer; derive NDVI/grid indicators only when a workflow requires them.",
  },
];

export const getLayer = (id: string) => LAYER_REGISTRY.find((layer) => layer.id === id);
