import type { AtlasSourceManifest } from "./types";

export const SOURCE_REGISTRY: AtlasSourceManifest[] = [
  {
    id: "kosis",
    name: "KOSIS 국가통계포털",
    category: "statistics",
    official: true,
    agentGrade: "B",
    accessMethods: ["api-key"],
    requiresEnv: ["KOSIS_API_KEY"],
    sourceFormats: ["json", "sdmx", "xml", "xls"],
    spatialLevels: ["national", "sido", "sigungu"],
    preferredFor: ["general-statistics", "regional-statistics", "time-series"],
    licenseNote: "Respect KOSIS OpenAPI terms, table-specific metadata and attribution requirements.",
    notes: "Broad official statistics provider. Normalize table-specific schemas into Atlas long-table statistics.",
  },
  {
    id: "sgis",
    name: "SGIS 통계지리정보서비스",
    category: "spatial-statistics",
    official: true,
    agentGrade: "B",
    accessMethods: ["oauth", "file-download"],
    requiresEnv: ["SGIS_CONSUMER_KEY", "SGIS_CONSUMER_SECRET"],
    sourceFormats: ["json", "shp", "txt", "csv"],
    spatialLevels: ["sido", "sigungu", "admin-dong", "grid-1km", "grid-500m", "grid-100m"],
    preferredFor: ["population", "business", "workers", "grid-statistics"],
    licenseNote: "Preserve SGIS source/reference year, native administrative codes and native grid IDs.",
    notes: "Primary spatial-statistics provider. Existing MVP already queries administrative-dong population/business statistics.",
  },
  {
    id: "data-go-kr",
    name: "공공데이터포털",
    category: "mixed",
    official: true,
    agentGrade: "B",
    accessMethods: ["api-key", "file-download"],
    requiresEnv: ["DATA_GO_KR_SERVICE_KEY"],
    sourceFormats: ["json", "xml", "csv", "shp", "file"],
    spatialLevels: ["national", "sido", "sigungu", "admin-dong", "feature"],
    preferredFor: ["official-facilities", "planning", "transport", "dataset-specific-public-data"],
    licenseNote: "License, traffic and reuse conditions must be stored per dataset because they differ across portal resources.",
    notes: "Portal-level registry; individual datasets still need dedicated adapters and manifests.",
  },
  {
    id: "vworld",
    name: "VWorld 공간정보오픈플랫폼",
    category: "vector",
    official: true,
    agentGrade: "B",
    accessMethods: ["api-key", "wms", "wfs", "wmts"],
    requiresEnv: ["VWORLD_API_KEY"],
    sourceFormats: ["json", "xml", "gml", "wms", "wfs", "wmts"],
    spatialLevels: ["national", "sido", "sigungu", "admin-dong", "legal-dong", "feature"],
    preferredFor: ["cadastral", "zoning", "planning", "national-spatial-layers", "map-reference"],
    fallbackIds: ["osm"],
    licenseNote: "Store layer-specific VWorld/public-data license and traffic metadata; do not assume every layer can be mirrored or redistributed.",
    notes: "Scriptable provider. Prefer WFS/Data API for extractable features and WMS/WMTS for display/verification. Official samples demonstrate API-key based WMTS, WMS, geocoding and 3D usage.",
  },
  {
    id: "osm",
    name: "OpenStreetMap / Overpass",
    category: "vector",
    official: false,
    agentGrade: "A",
    accessMethods: ["public-api"],
    sourceFormats: ["json", "osm"],
    spatialLevels: ["feature"],
    preferredFor: ["open-context", "roads", "buildings", "land-use", "green-water"],
    licenseNote: "ODbL attribution and share-alike obligations must be preserved where applicable.",
    notes: "Immediate open context/fallback, not a substitute for official Korean cadastral/planning/building records.",
  },
  {
    id: "hira",
    name: "건강보험심사평가원 의료기관",
    category: "facility",
    official: true,
    agentGrade: "B",
    accessMethods: ["api-key"],
    requiresEnv: ["DATA_GO_KR_SERVICE_KEY"],
    sourceFormats: ["xml", "json"],
    spatialLevels: ["feature"],
    preferredFor: ["hospital", "medical-facility"],
    licenseNote: "Preserve public-data provenance and API terms.",
    notes: "Existing MVP provider for official hospital/clinic facilities.",
  },
  {
    id: "localdata",
    name: "LOCALDATA 지방행정인허가",
    category: "facility",
    official: true,
    agentGrade: "C",
    accessMethods: ["file-download", "api-key"],
    sourceFormats: ["csv", "json", "xml"],
    spatialLevels: ["feature"],
    preferredFor: ["licensed-business", "open-close-history", "establishment-baseline"],
    licenseNote: "Dataset/license metadata must be preserved by business category and snapshot date.",
    notes: "Use full downloadable snapshots as baseline; OpenAPI is better treated as an incremental change feed.",
  },
  {
    id: "ngii-satellite",
    name: "국토지리정보원 / 국토위성",
    category: "raster",
    official: true,
    agentGrade: "C",
    accessMethods: ["api-key", "file-download", "manual-download"],
    sourceFormats: ["geotiff", "image", "metadata"],
    spatialLevels: ["raster-scene"],
    preferredFor: ["satellite", "high-resolution-context", "surface-reflectance", "derived-ndvi"],
    licenseNote: "Track product-specific download/API and reuse conditions; some products may require login/manual acquisition.",
    notes: "Keep domestic satellite products as independent raster layers. Normalize metadata and derive grid indicators only when needed.",
  },
  {
    id: "kakao",
    name: "Kakao Local",
    category: "poi",
    official: false,
    agentGrade: "B",
    accessMethods: ["api-key"],
    requiresEnv: ["KAKAO_REST_API_KEY"],
    sourceFormats: ["json"],
    spatialLevels: ["feature"],
    preferredFor: ["live-poi", "region-resolution"],
    licenseNote: "Use request-time lookup and respect Kakao API storage/display terms.",
    notes: "Useful live POI and coordinate-to-region provider; never treated as official establishment statistics.",
  },
  {
    id: "naver",
    name: "Naver Local Search",
    category: "poi",
    official: false,
    agentGrade: "B",
    accessMethods: ["api-key"],
    requiresEnv: ["NAVER_CLIENT_ID", "NAVER_CLIENT_SECRET"],
    sourceFormats: ["json"],
    spatialLevels: ["feature"],
    preferredFor: ["live-poi", "korean-place-search"],
    licenseNote: "Use request-time lookup and respect Naver API storage/display terms.",
    notes: "Korean place-name/business search complement.",
  },
  {
    id: "google",
    name: "Google Places",
    category: "poi",
    official: false,
    agentGrade: "B",
    accessMethods: ["api-key"],
    requiresEnv: ["GOOGLE_MAPS_API_KEY"],
    sourceFormats: ["json"],
    spatialLevels: ["feature"],
    preferredFor: ["live-poi", "global-place-detail"],
    licenseNote: "Google Maps Platform content/storage/display restrictions must be respected; do not treat results as an Atlas-owned POI database.",
    notes: "Optional global POI/detail complement.",
  },
];

export const getSource = (id: string) => SOURCE_REGISTRY.find((source) => source.id === id);
